# SourceHut Build Manifest
image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
    - nodejs
    - yarn
    - hut
environment:
    site: mastermind-game.lixquid.com
sources:
    - https://github.com/lixquid/app-mastermind-game
tasks:
    - build: |
          cd *
          yarn install
          yarn build
    - package: |
          cd *
          tar czvf dist.tgz dist
          hut pages publish -d $site dist.tgz
