# SourceHut Build Manifest
image: alpine
packages:
    - nodejs
    - yarn
sources:
    - https://github.com/lixquid/app-mastermind-game
tasks:
    - build: |
          cd app-mastermind-game
          yarn install
          yarn build
    - package: |
          cd app-mastermind-game
          tar czvf dist.tgz .
          acurl -f https://pages.sr.ht/publish/mastermind-game.lixquid.com -Fcontent=@dist.tgz
